[package]
name = "testbench"
version = "0.1.0"
authors = ["Jakob Demler <jdemler@curry-software.com>"]

[dependencies.perlin]
path = "../../perlin"

[dependencies]
time = "0.1.35"
getopts = "0.2.4"

[profile.release]
debug=true